name: deploy-to-github-pages
on:
  push:
    branches: [master]
jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: Deploy to Github Pages
    steps:
      - name: checkout site repo
        uses: actions/checkout@v3
      - name: deploy
        run: |
          npm i
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          npm run deploy
